function [f_dual] = dual_objective_func(dualvars, x_0, operators, learningparams, optparams)
global cnstData 
    Aysdp         = operators.A_EC'*dualvars.y_EC + operators.A_IC'*dualvars.y_IC + ...
                    operators.A_EV'*dualvars.y_EV + operators.A_IV'*dualvars.y_IV;
    Bysdp         = operators.B_EV'*dualvars.y_EV + operators.B_IV'*dualvars.y_IV;
    y_I           = [dualvars.y_IC;dualvars.y_IV];
    s_I           = [operators.s_IC; operators.s_IV];
    f_dual        = ( operators.b_EC'*dualvars.y_EC+ operators.b_EV'*dualvars.y_EV)...
                     - 1/2*norm(Aysdp + dualvars.S + dualvars.Z + x_0.u)^2 ...
                     - 1/2*(Bysdp+cnstData.Q*x_0.w_obeta)'*cnstData.Qinv*(Bysdp+cnstData.Q*x_0.w_obeta)...
                     - 1/2*norm(dualvars.v + y_I- x_0.st)^2-dualvars.v'*s_I+1/2*x_norm(x_0,cnstData.Q);
end