function [f_dual, g_y_E, g_y_I, g_S, g_Z, g_v] = dual_regwo_objective_grad(dualvars_k, x_0, operators, learningparams, optparams)
       b_E = [operators.b_EC;operators.b_EV];
       [f_dual, g_y_E, g_y_I, g_S, g_Z, g_v] ...
           = dual_regwo_objective_split_grad(b_E,dualvars_k.y_EC, dualvars_k.y_EV, dualvars_k.y_IC, dualvars_k.y_IV,...
                                            dualvars_k.S, dualvars_k.Z , dualvars_k.v, ...
                                            x_0, operators, learningparams, optparams);
end