function [almethod_list] = make_ActiveLearning_methods_list(distributional)
global cnstDefs
if ~distributional
almethod_list        = { ...
    {@randomsampling            ,false,@SVMtrain  ,@SVMtester, (1)     ,'RANDOM'               , cnstDefs.ALMETHOD_ID_RANDSAMPLE      , @getDUMMYEPstr},...
    {@quireactive               ,false,@SVMtrain  ,@SVMtester, (2)     ,'QUIRE'                , cnstDefs.ALMETHOD_ID_QUIRE           , @getDUMMYEPstr},...
    {@quire_clusterredactive    ,false,@SVMtrain  ,@SVMtester, (2)     ,'QUIREClust'           , cnstDefs.ALMETHOD_ID_QUIRECLUST    , @getDUMMYEPstr},...
    {@quireLAPLACIAN            ,false,@SVMtrain  ,@SVMtester, (2)     ,'QUIRELAP'             , cnstDefs.ALMETHOD_ID_QUIRELAP        , @getDUMMYEPstr},...
    {@mypycondxactive           ,false,@SVMtrain  ,@SVMtester, (11)    ,'PY|X'                 , cnstDefs.ALMETHOD_ID_MYPYCONDX       , @getDUMMYEPstr},...
    {@mybayesUncert             ,false,@SVMtrain  ,@SVMtester, (13)    ,'ARLPY|X'              , cnstDefs.ALMETHOD_ID_BAYESUNCERT     , @getDUMMYEPstr},...
    {@myspectralactive          ,false,@SVMtrain  ,@SVMtester, (12)    ,'ExpSPECT'             , cnstDefs.ALMETHOD_ID_SPECTRAL_E      , @getDUMMYEPstr},...
    {@myspectralactiveL2Boosting,false,@SVMtrain  ,@SVMtester, (14)    ,'SPCTL2BOOST'          , cnstDefs.ALMETHOD_ID_SPECTL2BOOST    , @getL2BoostEPstr},...
    {@FSimp2CompL2Boost         ,false,@SVMtrain  ,@SVMtester, (14)    ,'FSimComp'             , cnstDefs.ALMETHOD_ID_FSIMPCOMPL2BOOST, @getFSCL2BoostEPstr},...
    {@FSimp3CompL2Boost         ,false,@SVMtrain  ,@SVMtester, (14)    ,'FSim3Comp'            , cnstDefs.ALMETHOD_ID_FSIMP3COMPL2BOOST, @getFSCL3BoostEPstr},...
    {@SparseSimplePMAL          ,false,@SVMtrain  ,@SVMtester, (14)    ,'SPARSEPMAL'           , cnstDefs.ALMETHOD_ID_SPARSEPMAL,    @getSPPMALEPstr},...
    {@mySVDTruncateAL           ,false,@SVMtrain  ,@SVMtester, (15)    ,'SVDTR'                , cnstDefs.ALMETHOD_ID_SVDTRUNCATE     , @getDUMMYEPstr},...
    {@noactivelearning          ,false,@SVMtrain  ,@SVMtester, [ ]     ,'noAL'                 , cnstDefs.ALMETHOD_ID_NOACTIVE        , @getDUMMYEPstr},...
    {@uncertaintysamplingwrapper,false,@SVMtrain  ,@SVMtester, (3)     ,'UNCERT'               , cnstDefs.ALMETHOD_ID_UNCERTAINSAMPLE , @getDUMMYEPstr},...
    {@marginsampling            ,false,@SVMtrain  ,@SVMtester, (4)     ,'MARGIN'               , cnstDefs.ALMETHOD_ID_MARGIN          , @getDUMMYEPstr},...
    {@marginsampling            ,false,@SVMtrain  ,@SVMtester, (4)     ,'MARGIN'               , cnstDefs.ALMETHOD_ID_ADAPTREGMARGIN          , @getDUMMYEPstr},...
    {@TcybERIAL_PrLIBSVM        ,false,@SVMtrain  ,@SVMtester, (4)     ,'EXPREPINF'            , cnstDefs.ALMETHOD_ID_TCYBEXPLREPINFLIBSVMPROB          , @getDUMMYEPstr},...
    {@QDRBMAL                   ,false,@SVMtrain  ,@SVMtester, (4)     ,'BMDR'                 , cnstDefs.ALMETHOD_ID_BMDRACMTRANSKDD , @getDUMMYEPstr},...
    {@guss_harm_semi_al_wrapper ,false,@SVMtrain  ,@SVMtester, (5)     ,'HARMON'               , cnstDefs.ALMETHOD_ID_GUSSHARMONIC    , @getDUMMYEPstr},...
    {@maniadpat_exp_design      ,false,@SVMtrain  ,@SVMtester, (6)     ,'MANIFO'               , cnstDefs.ALMETHOD_ID_MAED            , @getDUMMYEPstr},...
    {@minimax_SVMAL             ,false,@SVMtrain  ,@SVMtester, (7)     ,'MXSVMAL'              , cnstDefs.ALMETHOD_ID_MINMAX_SVMAL    , @getDUMMYEPstr},...
    {@ALBoost_margin            ,false,@SVMtrain  ,@SVMtester, (7)     ,'MARGINBOOST'          , cnstDefs.ALMETHOD_ID_ACTIVEBOOST     , @getL2BoostEPstr},...
    {@ALFuncGradTikhonov        ,false,@SVMtrain  ,@SVMtester, (7)     ,'FUNCGRDSTAL'          , cnstDefs.ALMETHOD_ID_ACTIVETIKHONOV  , @getL2BoostEPstr},...
    {@AL2Boost_minmax           ,false,@SVMtrain  ,@SVMtester, (7)     ,'L2BOOSTMINMAX'        , cnstDefs.ALMETHOD_ID_L2BOOSTMINMAX      , @getL2BoostEPstr},...
    {@vari_logis_PMAL           ,false,@SVMtrain  ,@SVMtester, (7)     ,'VARLOGPMAL'           , cnstDefs.ALMETHOD_ID_VARLOGPMAL      , @getVARLOGPMAL},...
    {0                          ,true ,@ActiveDConvexRelaxOutlier          ,@testConvexRelaxClassifier, [8,9,10]','ActiveRobustlearningConvex',cnstDefs.ALMETHOD_ID_SOLVERROBUSTAL  , @getDUMMYEPstr},...
    {0                          ,true ,@ActiveOutlierSaddle15              ,@testConvexRelaxClassifier, [8,9,10]','ActiveRobustLearning'     , cnstDefs.ALMETHOD_ID_ALGORITHMROBUSTAL, @getDUMMYEPstr},...
    {0                          ,true ,@ActiveDiverseMultitask             ,@testConvexRelaxClassifier, [8,9,10]','ActiveDiverselearning'    , cnstDefs.ALMETHOD_ID_DIVERSEMULTITASK, @getDUMMYEPstr},...
    {0                          ,true ,@ActiveDConvexRelax2                ,@testConvexRelaxClassifier, [8,9,10]','ActiveConvexlearning'     , cnstDefs.ALMETHOD_ID_DCONVXRELAX2    , @getDUMMYEPstr},...
    {0                          ,true ,@ActiveCRSemiSVM03                  ,@ActiveDiverseMultitask   , [8,9,10]','ActiveAlternativelearning', cnstDefs.ALMETHOD_ID_CRSEMISVM03     , @getDUMMYEPstr},...
    {0                          ,true ,@ActiveDConvexRelaxOutlierProxADMM2 ,@testConvexRelaxClassifier, [8,9,10]','ActiveProxADMM'           , cnstDefs.ALMETHOD_ID_DCVXRELAXPROXADMM, @getDUMMYEPstr},...
    {0                          ,true ,@ActiveDConvexRelaxOutlier_abs_h    ,@testConvexRelaxClassifier, [8,9,10]','ActiveRLC_ABS_H'          , cnstDefs.ALMETHOD_ID_SOLVERRAL_ABS_H  , @getDUMMYEPstr},...
    {0                          ,true ,@ActiveDCvxRlxOt_abs_h_abs_p        ,@testConvexRelaxClassifier, [8,9,10]','ActiveRLC_ABS_H_ABS_P'    , cnstDefs.ALMETHOD_ID_SLVRRAL_ABS_H_ABS_P , @getDUMMYEPstr },...
    {0                          ,true ,@Simple_complex_classifier_1        ,@testConvexRelaxClassifier, [8,9,10]','Simple_Complex_classifier', cnstDefs.ALPASSIVE_ID_SIMPLECOMPLEXCLS_1 , @getDUMMYEPstr },...
    {0                          ,true ,@ActiveDConvexRelaxOutlierCPBased   ,@testConvexRelaxClassifier, [8,9,10]','ActiveRobustlearningConvex', cnstDefs.ALMETHOD_ID_SOLVERROBUSTALNORMONEPENALTY  , @getDUMMYEPstr},...
    };
else
almethod_list        = { ...
    {@DISTrandomsampling            ,false,@SMMtrain, @SMMtest, (1)     ,'DISTRAND'            , cnstDefs.DISTALMETHOD_ID_RANDSAMPLE      , @getDUMMYEPstr},...
    {@DISTquireactive               ,false,@SMMtrain, @SMMtest, (2)     ,'DISTQUIRE'           , cnstDefs.DISTALMETHOD_ID_QUIRE           , @getDUMMYEPstr},...
    {@DISTnoactivelearning          ,false,@SMMtrain, @SMMtest, [ ]     ,'DISTnoActiveleaning' , cnstDefs.DISTALMETHOD_ID_NOACTIVE        , @getDUMMYEPstr},...
    {@DISTuncertaintysamplingwrapper,false,@SMMtrain, @SMMtest, (3)     ,'DISTUNCERT'          , cnstDefs.DISTALMETHOD_ID_UNCERTAINSAMPLE , @getDUMMYEPstr},...
    {@DISTmarginsampling            ,false,@SMMtrain, @SMMtest, (4)     ,'DISTMARGIN'          , cnstDefs.DISTALMETHOD_ID_MARGIN          , @getDUMMYEPstr},...
    {@DISTguss_harm_semi_al_wrapper ,false,@SMMtrain, @SMMtest, (5)     ,'DISTHARM'            , cnstDefs.DISTALMETHOD_ID_GUSSHARMONIC    , @getDUMMYEPstr},...
    {@DISTmaniadpat_exp_design      ,false,@SMMtrain, @SMMtest, (6)     ,'DISTMANF'            , cnstDefs.DISTALMETHOD_ID_MAED            , @getDUMMYEPstr},...
    {@DISTminimax_SVMAL             ,false,@SMMtrain, @SMMtest, (7)     ,'DISTMXSV'            , cnstDefs.DISTALMETHOD_ID_MINMAX_SVMAL    , @getDUMMYEPstr},...
    {@HILBEMB_quireactive           ,false,@SMMtrain, @SMMtest, (8)     ,'HILBQUIRE'           , cnstDefs.HILBALMETHOD_ID_QUIRE           , @getDUMMYEPstr},...
    {@myHILBEMbayesUncert           ,false,@SMMtrain, @SMMtest, (9)     ,'ALBH'                , cnstDefs.HILBALMETHOD_ID_BAYESUNCT       , @getDUMMYEPstr},...
    {@BKE_AL                        ,false,@SMMtrain, @SMMtest, (10)    ,'ALBKE'               , cnstDefs.BKEAL_ID_BAYESUNCT              , @getDUMMYEPstr},...
    };
    
end
end